chore: implement the new bloc API changes for handling `BlocOverrides` , `BlocObserver,` and `HydratedBlocOverrides`.
NoScopeDevs/bloc_samples pull request #26
Opened 2021-11-22 19:42 UTC by yeikel16

Update dependencies :
- `bloc` to 8.0.1
- `flow_builder` to 0.0.6
- `flutter_bloc` to 8.0.0
- `bloc_test` to 9.0.1
- `mocktail` to 0.2.0

No longer implicitly requires `registerFallbackValue` for events and states

2021-11-23 03:52 UTC, marcossevilla requested changes
TAFN with lints and we should keep it as a draft until we get the bloc tests right

2021-11-23 03:52 UTC, marcossevilla commented on examples/form_flow/packages/formz_inputs/lib/src/pin.dart
> +        'Maximum length the pin requires to be valid.',
```suggestion
        'Pin’s maximum length defaults to 4.',
```

2021-11-23 03:52 UTC, marcossevilla commented on examples/launch_analytics/lib/main.dart
>  Future<void> main() async {
can we use a bootstrap function here too?

2021-11-23 03:52 UTC, marcossevilla commented on examples/launch_analytics/test/app/bloc/app_bloc_test.dart
> +            await expectLater(
we should revert these tests to use bloc_test before merging

2021-11-23 03:52 UTC, marcossevilla commented on examples/preference_navigation/analysis_options.yaml
> +    require_trailing_commas: false
why are we ignoring these?
```suggestion
```

2021-11-23 03:52 UTC, marcossevilla commented on examples/preference_navigation/packages/preferences/hive_preferences_repository/analysis_options.yaml
> +    require_trailing_commas: false
```suggestion

```

2021-11-23 03:52 UTC, marcossevilla commented on examples/preference_navigation/analysis_options.yaml
> +    library_private_types_in_public_api: false
```suggestion

```

2021-11-23 03:52 UTC, marcossevilla commented on examples/preference_navigation/packages/preferences/shared_preferences_repository/analysis_options.yaml
> +    require_trailing_commas: false
```suggestion

```

2021-11-23 03:52 UTC, marcossevilla commented on examples/profile_accounts/analysis_options.yaml
> +    library_private_types_in_public_api: false
```suggestion

```

2021-11-23 15:58 UTC, marcossevilla commented on examples/preference_navigation/packages/preferences/hive_preferences_repository/analysis_options.yaml
> +linter:
```suggestion

```

2021-11-23 15:58 UTC, marcossevilla commented on examples/preference_navigation/packages/preferences/hive_preferences_repository/analysis_options.yaml
> +  rules:
```suggestion

```

2021-11-23 15:59 UTC, marcossevilla commented on examples/preference_navigation/packages/preferences/shared_preferences_repository/analysis_options.yaml
> +  rules:
```suggestion

```

2021-11-23 15:59 UTC, marcossevilla commented on examples/preference_navigation/packages/preferences/shared_preferences_repository/analysis_options.yaml
> +linter:
```suggestion

```

2021-11-26 03:59 UTC, marcossevilla requested changes
TAFN, mostly reverting back the bloc tests, updating some versions to latest and some nits on bloc tests for BlocOverrides 👍

2021-11-26 03:59 UTC, marcossevilla commented on examples/preference_navigation/pubspec.yaml
> +  bloc: ^8.0.0
```suggestion
  bloc: ^8.0.1
```

2021-11-26 03:59 UTC, marcossevilla commented on examples/preference_navigation/pubspec.yaml
> +  bloc_test: ^9.0.0
```suggestion
  bloc_test: ^9.0.1
```

2021-11-26 03:59 UTC, marcossevilla commented on examples/launch_analytics/test/app/bloc/app_bloc_test.dart
>      group('AppAnalyticsChecked', () {
can we revert these to use bloc_test?

2021-11-26 03:59 UTC, marcossevilla commented on examples/launch_analytics/test/app/bloc/app_bloc_test.dart
> +          HydratedBlocOverrides.runZoned(
can we setup this override on the setUp method and just stub its dependencies on every test?

2021-11-27 02:07 UTC, yeikel16 commented on examples/launch_analytics/test/app/bloc/app_bloc_test.dart
>      group('AppAnalyticsChecked', () {
When I use blocTest I have no way of knowing the first state when creating the AppBloc instance. Any suggestion?

2021-11-27 05:38 UTC, marcossevilla commented on examples/launch_analytics/test/app/bloc/app_bloc_test.dart
>      group('AppAnalyticsChecked', () {
if we already have a test that verifies the initial state, we can remove the initial state from the list of expected emitted states

2021-12-07 16:50 UTC, marcossevilla approved these changes

2021-12-07 16:51 UTC, merged