refactor(form_flow): removed unnecessary parameters
NoScopeDevs/bloc_samples pull request #33
Opened 2022-05-24 02:22 UTC by yuruyuri16

2022-05-24 02:51 UTC, marcossevilla requested changes
I think there are some changes out of the scope of this PR (no scoped 😆 ) and the unnecessary parameters are actually necessary if we keep the user model without a copyWith method (which I prefer in this case to avoid deep copy on our bloc)

otherwise the actual changes look good and after those other observations are resolved, this PR can end up in fewer files 👍

2022-05-24 02:51 UTC, marcossevilla commented on examples/form_flow/README.md
> +<a href="https://github.com/felangel/bloc"><img src="https://tinyurl.com/bloc-library" alt="Bloc Library"></a>
```suggestion
```

this is a nice nit but as we already have this badge on the main README I think we should keep this one the way `very_good_cli` generated it

2022-05-24 02:51 UTC, marcossevilla commented on examples/form_flow/ios/Runner/Info.plist
> +	<true/>
🚀

2022-05-24 02:51 UTC, marcossevilla commented on examples/form_flow/lib/signup/bloc/sign_up_bloc.dart
> +    emit(state.copyWith(user: state.user.copyWith(email: email, name: name)));
can we go back to having user without copyWith? I prefer to enforce immutability in state objects rather than models themselves

2022-05-24 02:51 UTC, marcossevilla commented on examples/form_flow/lib/signup/bloc/sign_up_bloc.dart
> +    emit(state.copyWith(user: state.user.copyWith(biography: event.biography)));
same as above

2022-05-24 02:51 UTC, marcossevilla commented on examples/form_flow/lib/signup/bloc/sign_up_bloc.dart
> +    final pin = event.pin;
```suggestion
```

2022-05-24 02:51 UTC, marcossevilla commented on examples/form_flow/lib/signup/bloc/sign_up_bloc.dart
> +    emit(state.copyWith(user: state.user.copyWith(pin: pin), complete: true));
same as above

2022-05-24 02:51 UTC, marcossevilla commented on examples/form_flow/lib/signup/credentials/cubit/credentials_cubit.dart
> -        status: Formz.validate([state.email, name]),
I think `state.email` is still necessary as the email input needs to be validated too

2022-05-24 02:51 UTC, marcossevilla commented on examples/form_flow/lib/signup/credentials/cubit/credentials_cubit.dart
> -        status: Formz.validate([email, state.name]),
I think `state.name` is still necessary as the email input needs to be validated too

2022-05-24 02:51 UTC, marcossevilla commented on examples/form_flow/packages/profile/lib/src/models/user.dart
> +  User copyWith({
sorry I didn't catch this earlier but I'd prefer that we enforce immutability in state objects rather than models here

2022-05-24 02:51 UTC, marcossevilla commented on examples/form_flow/pubspec.yaml
> +  flutter: "3.0.1"
can we roll back and maybe do this upgrade on a separate PR?

2022-05-24 02:52 UTC, marcossevilla commented on .github/workflows/examples.yaml
> +          flutter-version: '3.0.1'
can we do this on another PR?

2022-05-24 02:55 UTC, yuruyuri16 commented on examples/form_flow/lib/signup/credentials/cubit/credentials_cubit.dart
> -        status: Formz.validate([email, state.name]),
The function ```changeEmail``` is called only when the email has changed so the only thing to validate would be the email.

2022-05-24 03:03 UTC, marcossevilla commented on examples/form_flow/lib/signup/credentials/cubit/credentials_cubit.dart
> -        status: Formz.validate([email, state.name]),
yeah but the status represents if every field on the form is validated, which is email and name in this case

2022-05-24 03:12 UTC, yuruyuri16 commented on examples/form_flow/lib/signup/credentials/cubit/credentials_cubit.dart
> -        status: Formz.validate([email, state.name]),
Got it!

2022-06-02 20:09 UTC, marcossevilla approved these changes
lgtm 🚀

2022-06-02 20:09 UTC, merged