deps(profile_accounts): upgrade to flutter 3.10.2 and dart 3
NoScopeDevs/bloc_samples pull request #38
Opened 2023-05-29 02:09 UTC by elianortega

2023-05-30 04:18 UTC, elianortega commented
@marcossevilla I think is now ready.

Just like we talked earlier there is one workflow file for the profile accounts example, the idea would be to replicate this for every example and once we update all we could delete the old workflow file and melos file.

2023-05-30 20:19 UTC, marcossevilla requested changes
looking great overall, lmk what you think 👍

2023-05-30 20:19 UTC, marcossevilla commented on .github/workflows/examples.yaml
> +          flutter pub global activate melos 2.9.0
why are we specifying a version now?

2023-05-30 20:19 UTC, marcossevilla commented on .github/workflows/examples.yaml
> +          channel: "stable"
any difference on using double quotes instead of single ones?

2023-05-30 20:19 UTC, marcossevilla commented on .github/workflows/profile_accounts.yaml
> +      flutter_channel: "stable"
can we specify a version instead of latest stable?

2023-05-30 20:19 UTC, marcossevilla commented on examples/profile_accounts/lib/profile/bloc/profile_bloc.dart
> -      emit(const ProfileError());
what about the error state? I think we can simplify these ifs by using [patterns](https://dart.dev/language/patterns)

2023-05-30 20:19 UTC, marcossevilla commented on examples/profile_accounts/lib/profile/bloc/profile_event.dart
> +sealed class ProfileEvent extends Equatable {
💙

2023-05-30 20:19 UTC, marcossevilla commented on examples/profile_accounts/lib/profile/bloc/profile_event.dart
> +final class ProfileCurrentAccountChanged extends ProfileEvent {
should we add this same `final` modifier to `ProfileAccountAdded`?

2023-05-30 20:19 UTC, marcossevilla commented on examples/profile_accounts/test/profile/view/profile_form_test.dart
> +                    mockEmail,
```suggestion
                  .having(
                    (e) => e.account.name,
                    'name',
                    fakeName,
                  )
                  .having(
                    (e) => e.account.email,
                    'email',
                    fakeEmail,
```

2023-05-30 20:19 UTC, marcossevilla commented on examples/profile_accounts/test/profile/view/profile_form_test.dart
> +                    mockEmail,
we could create a `FakeProfile` object too

2023-05-30 20:19 UTC, marcossevilla requested changes
looking great overall, lmk what you think 👍

2023-05-31 02:01 UTC, elianortega commented on .github/workflows/examples.yaml
> +          flutter pub global activate melos 2.9.0
when doing `flutter pub global activate` it will activate the latest available version, but as we want the old examples to still run on flutter 3.3 which uses dart < 3, we can't use the latest `melos` as it requires dart >= 3, which is why we need to specify the `melos 2.9.0` version

2023-05-31 02:11 UTC, elianortega commented on .github/workflows/examples.yaml
> +          channel: "stable"
no, I think it was from some copy paste I did, but the new CI is also using double quotes so I think it can stay like this, at the end it is going to get deleted 👀

2023-05-31 02:49 UTC, elianortega commented on examples/profile_accounts/test/profile/view/profile_form_test.dart
> +                    mockEmail,
The issue is the the `User()` is created in the `onPressed` which means a new User with unique id is created every time, also I think that the idea is to also test that the values inputed to the form are the same that are used to create the `User`. 

But can you expand on how the `FakeProfile` could help here?

2023-05-31 02:49 UTC, elianortega commented on examples/profile_accounts/lib/profile/bloc/profile_event.dart
> +final class ProfileCurrentAccountChanged extends ProfileEvent {
I did, but then is not possible to implement it and create the `Fake` in `profile_form_test.dart`.

2023-05-31 23:37 UTC, marcossevilla approved these changes

2023-06-01 02:20 UTC, merged