deps(preference_navigation): upgrade to flutter 3.10.5 and dart 3
NoScopeDevs/bloc_samples pull request #41
Opened 2023-07-21 00:23 UTC by elianortega

2023-07-21 12:47 UTC, marcossevilla requested changes

2023-07-21 12:47 UTC, marcossevilla commented on examples/preference_navigation/lib/home/view/home_page.dart
> +  final Map<dynamic, dynamic> preferences;
```suggestion
  final Map<String, dynamic> preferences;
```
should this be `<String, dynamic>` based on the key-value approach?

2023-07-21 12:47 UTC, marcossevilla commented on examples/preference_navigation/lib/home/view/home_page.dart
> +  static Route<void> go() {
```suggestion
  static Route<void> route() {
```
nit

2023-07-21 12:47 UTC, marcossevilla commented on examples/preference_navigation/lib/preferences/view/preferences_page.dart
> +  static Route<void> go() {
```suggestion
  static Route<void> route() {
```

2023-07-21 12:47 UTC, marcossevilla commented on examples/preference_navigation/lib/start/view/start_page.dart
> +  static Route<void> go() {
```suggestion
  static Route<void> route() {
```

2023-07-21 13:01 UTC, elianortega commented on examples/preference_navigation/lib/home/view/home_page.dart
> +  final Map<dynamic, dynamic> preferences;
Yes it should.

2023-07-24 08:55 UTC, marcossevilla approved these changes

2023-07-24 13:35 UTC, merged